
import koneksi.koneksi;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Infinix
 */
public class Dashboard extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;

    public Dashboard() {
        super("Dashboard");
        initComponents();
        conn=koneksi.getKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn_btndashboard = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        pn_btnAnggota = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_dashboard1 = new javax.swing.JLabel();
        pn_btnBuku = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_dashboard2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_btnPeminjaman = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_dashboard4 = new javax.swing.JLabel();
        pn_btnPengembalian = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_dashboard5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_layout = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(255, 204, 153));
        pn_kiri.setPreferredSize(new java.awt.Dimension(200, 768));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\image\\bookshelf4.png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("LIBRARY SYSTEM");

        pn_btndashboard.setBackground(new java.awt.Color(255, 204, 153));
        pn_btndashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btndashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btndashboardMouseEntered(evt);
            }
        });

        pn_line.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\image\\imac.png")); // NOI18N

        btn_dashboard.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btndashboardLayout = new javax.swing.GroupLayout(pn_btndashboard);
        pn_btndashboard.setLayout(pn_btndashboardLayout);
        pn_btndashboardLayout.setHorizontalGroup(
            pn_btndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btndashboardLayout.createSequentialGroup()
                .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dashboard)
                .addGap(31, 31, 31))
        );
        pn_btndashboardLayout.setVerticalGroup(
            pn_btndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btndashboardLayout.createSequentialGroup()
                .addGroup(pn_btndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_btndashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_btndashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_dashboard)))
                .addGap(16, 16, 16))
        );

        pn_btnAnggota.setBackground(new java.awt.Color(255, 204, 153));
        pn_btnAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnAnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnAnggotaMouseExited(evt);
            }
        });

        pn_line1.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\image\\people.png")); // NOI18N

        btn_dashboard1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn_dashboard1.setText("Anggota");
        btn_dashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboard1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboard1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnAnggotaLayout = new javax.swing.GroupLayout(pn_btnAnggota);
        pn_btnAnggota.setLayout(pn_btnAnggotaLayout);
        pn_btnAnggotaLayout.setHorizontalGroup(
            pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(btn_dashboard1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_btnAnggotaLayout.setVerticalGroup(
            pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                .addGroup(pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_dashboard1)))
                .addGap(16, 16, 16))
        );

        pn_btnBuku.setBackground(new java.awt.Color(255, 204, 153));
        pn_btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnBukuMouseExited(evt);
            }
        });

        pn_line2.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-nook-32.png")); // NOI18N

        btn_dashboard2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn_dashboard2.setText("Buku");
        btn_dashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboard2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboard2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboard2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnBukuLayout = new javax.swing.GroupLayout(pn_btnBuku);
        pn_btnBuku.setLayout(pn_btnBukuLayout);
        pn_btnBukuLayout.setHorizontalGroup(
            pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnBukuLayout.createSequentialGroup()
                .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(btn_dashboard2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_btnBukuLayout.setVerticalGroup(
            pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnBukuLayout.createSequentialGroup()
                .addGroup(pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_btnBukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_dashboard2)))
                .addGap(16, 16, 16))
        );

        jLabel8.setBackground(new java.awt.Color(255, 204, 153));
        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Transaksi");

        pn_btnPeminjaman.setBackground(new java.awt.Color(255, 204, 153));
        pn_btnPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPeminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnPeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPeminjamanMouseExited(evt);
            }
        });

        pn_line4.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-return-book-32.png")); // NOI18N

        btn_dashboard4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn_dashboard4.setText("Peminjaman");
        btn_dashboard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboard4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboard4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboard4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPeminjamanLayout = new javax.swing.GroupLayout(pn_btnPeminjaman);
        pn_btnPeminjaman.setLayout(pn_btnPeminjamanLayout);
        pn_btnPeminjamanLayout.setHorizontalGroup(
            pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPeminjamanLayout.createSequentialGroup()
                .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dashboard4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_btnPeminjamanLayout.setVerticalGroup(
            pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel9)
                .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn_btnPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_dashboard4))
        );

        pn_btnPengembalian.setBackground(new java.awt.Color(255, 204, 153));
        pn_btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnPengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPengembalianMouseExited(evt);
            }
        });

        pn_line5.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\image\\buku tebalik.png")); // NOI18N

        btn_dashboard5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn_dashboard5.setText("Pengembalian");
        btn_dashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboard5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboard5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboard5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPengembalianLayout = new javax.swing.GroupLayout(pn_btnPengembalian);
        pn_btnPengembalian.setLayout(pn_btnPengembalianLayout);
        pn_btnPengembalianLayout.setHorizontalGroup(
            pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPengembalianLayout.createSequentialGroup()
                .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dashboard5)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pn_btnPengembalianLayout.setVerticalGroup(
            pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel10)
                .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn_btnPengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_dashboard5))
        );

        jLabel13.setBackground(new java.awt.Color(255, 204, 153));
        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Master Data");

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pn_btnBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_btnAnggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_btndashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pn_btnPengembalian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_btnPeminjaman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_kiriLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(pn_btndashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_btnAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_btnBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(pn_btnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_kiriLayout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(jLabel13)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_layout.setBackground(new java.awt.Color(0, 204, 204));
        pn_layout.setPreferredSize(new java.awt.Dimension(1166, 70));

        javax.swing.GroupLayout pn_layoutLayout = new javax.swing.GroupLayout(pn_layout);
        pn_layout.setLayout(pn_layoutLayout);
        pn_layoutLayout.setHorizontalGroup(
            pn_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1181, Short.MAX_VALUE)
        );
        pn_layoutLayout.setVerticalGroup(
            pn_layoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_layout, java.awt.BorderLayout.PAGE_START);

        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1397, 816));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pn_btnPengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPengembalianMouseExited
        // TODO add your handling code here:
        pn_btnPengembalian.setBackground(new Color(255,204,153));
        pn_line5.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_pn_btnPengembalianMouseExited

    private void pn_btnPengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPengembalianMouseEntered
        // TODO add your handling code here:
        pn_btnPengembalian.setBackground(new Color(250,250,250));
        pn_line5.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_pn_btnPengembalianMouseEntered

    private void pn_btnPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPengembalianMouseClicked
        // TODO add your handling code here:

        pn_btnBuku.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(0,102,153));

        pn_utama.removeAll();
        pn_utama.add(new menuPengembalian());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_btnPengembalianMouseClicked

    private void btn_dashboard5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard5MouseExited

    private void btn_dashboard5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard5MouseEntered

    private void btn_dashboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard5MouseClicked

    private void pn_btnPeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPeminjamanMouseExited
        // TODO add your handling code here:
        pn_btnPeminjaman.setBackground(new Color(255,204,153));
        pn_line4.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_pn_btnPeminjamanMouseExited

    private void pn_btnPeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPeminjamanMouseEntered
        // TODO add your handling code here:
        pn_btnPeminjaman.setBackground(new Color(250,250,250));
        pn_line4.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_pn_btnPeminjamanMouseEntered

    private void pn_btnPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPeminjamanMouseClicked
        // TODO add your handling code here:

        pn_btnBuku.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(0,102,153));

        pn_utama.removeAll();
        pn_utama.add(new menuPeminjaman());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pn_btnPeminjamanMouseClicked

    private void btn_dashboard4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard4MouseExited

    private void btn_dashboard4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard4MouseEntered

    private void btn_dashboard4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard4MouseClicked

    private void pn_btnBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnBukuMouseExited
        // TODO add your handling code here:
        pn_btnBuku.setBackground(new Color(255,204,153));
        pn_line2.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_pn_btnBukuMouseExited

    private void pn_btnBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnBukuMouseEntered
        // TODO add your handling code here:
        pn_btnBuku.setBackground(new Color(250,250,250));
        pn_line2.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_pn_btnBukuMouseEntered

    private void pn_btnBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnBukuMouseClicked
        // TODO add your handling code here:

        pn_btnBuku.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(0,102,153));

        pn_utama.removeAll();
        pn_utama.add(new menuBuku());
        pn_utama.repaint();
        pn_utama.revalidate();

    }//GEN-LAST:event_pn_btnBukuMouseClicked

    private void btn_dashboard2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard2MouseExited

    private void btn_dashboard2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard2MouseEntered

    private void btn_dashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard2MouseClicked

    private void pn_btnAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnAnggotaMouseExited
        // TODO add your handling code here:
        pn_btnAnggota.setBackground(new Color(255,204,153));
        pn_line1.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_pn_btnAnggotaMouseExited

    private void pn_btnAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnAnggotaMouseEntered
        // TODO add your handling code here:
        pn_btnAnggota.setBackground(new Color(250,250,250));
        pn_line1.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_pn_btnAnggotaMouseEntered

    private void pn_btnAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnAnggotaMouseClicked
        // TODO add your handling code here:
        pn_utama.removeAll();
        pn_utama.add(new menuAnggota());
        pn_utama.repaint();
        pn_utama.revalidate();

    }//GEN-LAST:event_pn_btnAnggotaMouseClicked

    private void btn_dashboard1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard1MouseExited

    private void btn_dashboard1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dashboard1MouseEntered

    private void pn_btndashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btndashboardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_btndashboardMouseEntered

    private void pn_btndashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btndashboardMouseClicked
        // TODO add your handling code here:
        pn_btndashboard.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(0,102,153));

        pn_utama.removeAll();
        pn_utama.add(new menuDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();

    }//GEN-LAST:event_pn_btndashboardMouseClicked

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        pn_btndashboard.setBackground(new Color(255,204,153));
        pn_line.setBackground(new Color(255,204,153));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        pn_btndashboard.setBackground(new Color(250,250,250));
        pn_line.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        pn_btndashboard.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(0,102,153));

        pn_utama.removeAll();
        pn_utama.add(new menuDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_dashboard1;
    private javax.swing.JLabel btn_dashboard2;
    private javax.swing.JLabel btn_dashboard4;
    private javax.swing.JLabel btn_dashboard5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pn_btnAnggota;
    private javax.swing.JPanel pn_btnBuku;
    private javax.swing.JPanel pn_btnPeminjaman;
    private javax.swing.JPanel pn_btnPengembalian;
    private javax.swing.JPanel pn_btndashboard;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_layout;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
