
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Infinix
 */
public class menuPeminjaman extends javax.swing.JPanel {

    private final Connection conn;

    public menuPeminjaman() {
        initComponents();
        
        conn= koneksi.getKoneksi();
        setTableModel();
        setTableModelSementara();
        loadDataSementara();
        loadData();   
        actionButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        dateChooser2 = new com.raven.datechooser.DateChooser();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnTambah = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        txtSearch = new javax.swing.JTextField();
        panelAdd = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnHapus = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();
        txtId = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTglKembali = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtIdAnggota = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtNamaAnggota = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtEmailAnggota = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtTeleponAnggota = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtIdBuku = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtJudulBuku = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtPengarangBuku = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btnSetAnggota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataSementara = new javax.swing.JTable();
        btnUbah = new rojerusan.RSMaterialButtonRectangle();
        btnSave2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel33 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btnSetBuku = new javax.swing.JButton();

        dateChooser1.setTextRefernce(txtTglPinjam);

        dateChooser2.setTextRefernce(txtTglKembali);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1141, 676));
        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setPreferredSize(new java.awt.Dimension(1141, 676));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-nook-32.png")); // NOI18N
        jLabel13.setText("Data Peminjaman Buku Perpustakaan");

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Transaksi - Peminjaman");

        btnTambah.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-refuse-32.png")); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(255, 0, 102));
        rSMaterialButtonRectangle2.setText("Hapus");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(255, 153, 102));
        rSMaterialButtonRectangle3.setText("Batal");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        txtSearch.setText("Search");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSMaterialButtonRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        panelMain.add(panelView, "card2");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));
        panelAdd.setPreferredSize(new java.awt.Dimension(1141, 676));

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-people-32.png")); // NOI18N
        jLabel15.setText("Tambah Data Peminjaman Buku Perpustakaan");

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Transaksi - Peminjaman");

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-refuse-32.png")); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle7.setBackground(new java.awt.Color(255, 153, 102));
        rSMaterialButtonRectangle7.setText("Batal");
        rSMaterialButtonRectangle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle7ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel19.setText("ID");

        jLabel20.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel20.setText("Tanggal Pinjam");

        jLabel23.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel23.setText("Tanggal Kembali");

        jLabel25.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel25.setText("ID Anggota");

        jLabel26.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel26.setText("Nama");

        jLabel27.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel27.setText("Email");

        jLabel28.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel28.setText("Telepon");

        jLabel29.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel29.setText("ID Buku");

        jLabel30.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel30.setText("Judul");

        jLabel31.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel31.setText("Pengarang");

        jLabel32.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel32.setText("Jumlah");

        btnSetAnggota.setText("...");
        btnSetAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetAnggotaActionPerformed(evt);
            }
        });

        tblDataSementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDataSementara);

        btnUbah.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-refuse-32.png")); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnSave2.setIcon(new javax.swing.ImageIcon("C:\\image\\icons8-refuse-32.png")); // NOI18N
        btnSave2.setText("SIMPAN");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel33.setText("Total Pinjam");

        lbTotal.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lbTotal.setText("TOTAL");
        lbTotal.setMaximumSize(new java.awt.Dimension(100, 50));
        lbTotal.setMinimumSize(new java.awt.Dimension(100, 50));
        lbTotal.setPreferredSize(new java.awt.Dimension(100, 50));

        btnSetBuku.setText("...");
        btnSetBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAddLayout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(rSMaterialButtonRectangle7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(111, 111, 111))
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(336, 336, 336)
                            .addComponent(jLabel23)
                            .addGap(18, 18, 18)
                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32)
                                .addComponent(jLabel33)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelAddLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAddLayout.createSequentialGroup()
                                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(panelAddLayout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIdAnggota)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnSetAnggota)
                                            .addGap(3, 3, 3))
                                        .addGroup(panelAddLayout.createSequentialGroup()
                                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel28)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel26))
                                            .addGap(44, 44, 44)
                                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTeleponAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtEmailAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelAddLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(18, 18, 18)
                                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(38, 38, 38)
                                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelAddLayout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelAddLayout.createSequentialGroup()
                                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel31)
                                                .addComponent(jLabel29)
                                                .addComponent(jLabel30))
                                            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelAddLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtPengarangBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panelAddLayout.createSequentialGroup()
                                                            .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(btnSetBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                    .addGap(79, 79, 79))
                                .addComponent(jScrollPane2))))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(31, 31, 31)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMaterialButtonRectangle7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPengarangBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31)))
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSetAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29)
                                .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSetBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTeleponAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMain.add(panelAdd, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSMaterialButtonRectangle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle7ActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_rSMaterialButtonRectangle7ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(btnHapus.getText().equals("TAMBAH"))
        {
            btnHapus.setText("SIMPAN");
        }
        else if (btnHapus.getText().equals("SIMPAN"))
        {
            insertData();
            insertDataDetail();
 
        }
        else if (btnHapus.getText().equals("PERBARUI"))
        {
            updateData();
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:\
        searchData();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnSetAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetAnggotaActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        // TODO add your handling code here
 
            insertData();
            insertDataDetail();
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);
            
            resetForm();
        
        
        
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void btnSetBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetBukuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnHapus;
    private rojerusan.RSMaterialButtonRectangle btnSave2;
    private javax.swing.JButton btnSetAnggota;
    private javax.swing.JButton btnSetBuku;
    private rojerusan.RSMaterialButtonRectangle btnTambah;
    private rojerusan.RSMaterialButtonRectangle btnUbah;
    private com.raven.datechooser.DateChooser dateChooser1;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private javax.swing.JTable tblDataSementara;
    private javax.swing.JTextField txtEmailAnggota;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdAnggota;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaAnggota;
    private javax.swing.JTextField txtPengarangBuku;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTeleponAnggota;
    private javax.swing.JTextField txtTglKembali;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables

    
    
    
    private void loadData() {
      getData((DefaultTableModel) jTable1.getModel());
    }
    
    private void loadDataSementara(){
        getDataSementara((DefaultTableModel) tblDataSementara.getModel());
    }

    

    

    private void setTableModel() {
        DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID","Tanggal Pinjam","Tanggal Kembali","Total Pinjam", "Anggota"},
                0
        );
        
        jTable1.setModel(model);
    }

    
    private void setTableModelSementara() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID", "Judul Buku", "Pengarang", "Jumlah Pinjam"}, 0
    );
    tblDataSementara.setModel(model);
}

    
    private void getDataSementara(DefaultTableModel model) {
        model.setRowCount(0);
        
        try{
            String sql = "SELECT * FROM sementara";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet  rs = st.executeQuery();
                
                while (rs.next()){
                    String idBuku= rs.getString("id_buku");
                    String judulBuku = rs.getString("judul_buku");
                    String pengarangBuku = rs.getString("pengarang");
                    String jumlahPinjam = rs.getString("jumlah_pinjam");
              
                    
                    Object[] rowData = {idBuku, judulBuku, pengarangBuku, jumlahPinjam};
                    model.addRow(rowData);
                    
                }
            }
        }catch (SQLException e) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, e);
            
        }
            }
    


    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
        try{
            String sql = "SELECT * FROM peminjaman";
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet  rs = st.executeQuery();
                
                while (rs.next()){
                    String idPeminjaman = rs.getString("id_peminjaman");
                    String tanggalPinjam = rs.getString("tgl_peminjaman");
                    String tanggalKembali = rs.getString("tgl_pengembalian");
                    String totalPinjam = rs.getString("total_pinjam");
                    String namaAnggota = rs.getString("nama_anggota");
                    
                    Object[] rowData = {idPeminjaman, tanggalPinjam, tanggalKembali, totalPinjam, namaAnggota};
                    model.addRow(rowData);
                    
                }
            }
        }catch (SQLException e) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, e);
            
        }
            }
    
    private void getDataDetail(DefaultTableModel model) {
        model.setRowCount(0);
        
        try{
            String sql = "SELECT pmd.id_peminjaman, bk.id_buku, bk.judul_buku, pmd.jumlah_pinjam, pmd.status_peminjaman\n"+
                    "FROM detail_peminjaman pmd\n"+
                    "INNER JOIN buku bk ON bk.id_buku = pmd.id_buku\n" +                   
                    "WHERE pmd.id_peminjaman = ?"+
                    "ORDER BY pmd.id_peminjaman ASC";
                      
            try (PreparedStatement st = conn.prepareStatement(sql)){
                ResultSet  rs = st.executeQuery();
                
                while (rs.next()) {
                    String idPeminjaman = rs.getString("id_peminjaman");
                    String idBuku = rs.getString("id_buku");
                    String judulBuku = rs.getString("judul_buku");
                    String jumlahPinjam = rs.getString("jumlah_pinjam");
                    String status = rs.getString("status_peminjaman");

                    Object[] rowData = {idPeminjaman, idBuku, judulBuku, jumlahPinjam, status};
                    model.addRow(rowData);

                }
            }
        }catch (SQLException e) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, e);
            
        }
            }
    
 
        
    private void setAnggota(){
        boolean closable = true;
        menuAnggota3 anggota = new menuAnggota3(null, closable);
        anggota.setVisible(true);
        
        txtIdAnggota.setText(anggota.getIdAnggota());
        txtNamaAnggota.setText(anggota.getNamaAnggota());
        txtEmailAnggota.setText(anggota.getEmailAnggota());
        txtTeleponAnggota.setText(anggota.getTeleponAnggota());
        
        txtIdAnggota.setEnabled(false);
        txtNamaAnggota.setEnabled(false);
        txtEmailAnggota.setEnabled(false);
        txtTeleponAnggota.setEnabled(false);
    }
    
    private void setBuku(){
        boolean closable = true;
        menuBuku3 buku = new menuBuku3(null, closable);
        buku.setVisible(true);
        
        txtIdBuku.setText(buku.getIdBuku());
        txtJudulBuku.setText(buku.getJudulBuku());
        txtPengarangBuku.setText(buku.getPengarangBuku());
       
        
        txtIdBuku.setEnabled(false);
        txtJudulBuku.setEnabled(false);
        txtPengarangBuku.setEnabled(false);
       
        
    }

    private void insertDataSementara() {
        String idBuku = txtId.getText();
        String judulBuku = txtJudulBuku.getText();
        String pengarangBuku = txtPengarangBuku.getText();
        String jumlahPinjam = txtJumlah.getText();
        String statusPinjam = "Sedang Dipinjam";

        
        if(idBuku.isEmpty()|| judulBuku.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus di isi");
            return;
        }
        try {
            String sql = "INSERT INTO sementara (id_buku,judul_buku,pengarang,jumlah_pinjam, status_pinjam) values (?,?,?,?,?)";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, idBuku);
                st.setString(2, judulBuku);
                st.setString(3, pengarangBuku);
                st.setString(4, jumlahPinjam);
                st.setString(5, statusPinjam);
                
                st.executeUpdate();
                
                int totalPinjam = getTotalPinjam();
                lbTotal.setText(String.valueOf(totalPinjam));
                loadDataSementara();
                
                }
                
        }catch (HeadlessException | SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error saat menyimpan data: " + e.getMessage());
        }
    }
    
    private int getTotalPinjam(){
        int lbTotal = 0;
        
        try{
            String sql = "SELECT SUM(jumlah_pinjam) as total FROM sementara";
            try(PreparedStatement st = conn.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery();
                if (rs.next()){
                    lbTotal = rs.getInt("total");
                }
            }
        } catch (SQLException e){
                    e.printStackTrace();

        }
        return lbTotal;
    }

    
 
    
    private void insertData() {
        String idPeminjaman = txtId.getText();
        String totalPinjam = lbTotal.getText();
        String NamaAnggota = txtNamaAnggota.getText();

    
    String tglPinjam, tglKembali;
    try {
        SimpleDateFormat fromUser = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat toDb = new SimpleDateFormat("yyyy-MM-dd");

        tglPinjam = toDb.format(fromUser.parse(txtTglPinjam.getText()));
        tglKembali = toDb.format(fromUser.parse(txtTglKembali.getText()));
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal salah!");
        return;
    }
        if(idPeminjaman.isEmpty() || tglPinjam.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua kolom harus di isi !");
            return;
        }
        
        try {
            String sql = "INSERT INTO peminjaman (id_peminjaman, tgl_peminjaman, tgl_pengembalian, total_pinjam, nama_anggota) VALUES (?,?,?,?,?)";
            try(PreparedStatement st = conn.prepareStatement(sql)){
                st.setString(1, idPeminjaman);
                st.setString(2, tglPinjam);
                st.setString(3, tglKembali);
                st.setString(4, totalPinjam);
                st.setString(5, NamaAnggota);
                
                int rowInserted = st.executeUpdate();
                if(rowInserted > 0 ) {
                    JOptionPane.showMessageDialog(this, "Data berhasil di tambahkan");
                }
            }
            } catch (SQLException e){
                Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, e);
            }

}

        
    

    private void updateData() {
        
    }

    private void resetForm() {
       

    }

    private void deleteData() {
        int selectedRow = jTable1.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data?","Konfirmasi Hapus data", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String id = jTable1.getValueAt(selectedRow, 0).toString();
            try{
                String sql = "DELETE FROM peminjaman WHERE id_peminjaman=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, id);
                
                int rowDeleted = ps.executeUpdate();
                
                if(rowDeleted> 0){
                    JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
                    resetForm();
                    loadData();
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                }
            ps.close();
        } catch (SQLException e){
                Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null,e);
                }
            }
        }

    private void searchData() {
        String kataKunci = txtSearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        try{
            String sql = "SELECT * FROM peminjaman WHERE id_peminjaman LIKE ? OR nama_anggota LIKE ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, "%" + kataKunci + "%");
            st.setString(2, "%" + kataKunci + "%");
            ResultSet rs = st.executeQuery();
            
            while (rs.next()){
                String idPeminjaman = rs.getString("id_peminjaman");
                    String tanggalPinjam = rs.getString("tgl_peminjaman");
                    String tanggalKembali = rs.getString("tgl_pengembalian");
                    String totalPinjam = rs.getString("total_pinjam");
                    String namaAnggota = rs.getString("nama_anggota");
                
                Object[] rowData = {idPeminjaman,tanggalPinjam,tanggalKembali,totalPinjam,namaAnggota};
                model.addRow(rowData);
            }
            
            rs.close();
            st.close();
        
    } catch (SQLException e) {
        Logger.getLogger(menuBuku.class.getName()).log(Level.SEVERE, null, e);
    
}      
    }

   private void actionButton() {
    btnSetAnggota.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            setAnggota();
        }
    });

    btnSetBuku.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            setBuku();
        }
    });
    
    txtJumlah.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            insertDataSementara();
        }
    });
}

    private void insertDataDetail() {
        String idPeminjaman = txtId.getText();
  
        
        
        try {
            String sql = "INSERT INTO detail_peminjaman (id_peminjaman, id_buku, jumlah_pinjam, status_peminjaman) SELECT '"+idPeminjaman+"', id_buku, jumlah_pinjam, status_pinjam FROM sementara";
            try(PreparedStatement st = conn.prepareStatement(sql)){


                st.executeUpdate();

                
            }
            } catch (SQLException e){
                Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, e);
            }

    }}

   
        

